export interface ProductReview {
  id: string;
  name: string;
  rating: number;
  date: string;
  comment: string;
}

export interface EcommerceLinks {
  shopee?: string;
  tokopedia?: string;
  lazada?: string;
  tiktokShop?: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  tags: string[];
  stock: "Tersedia" | "Habis";
  unit: string;
  image: string;
  images: string[];
  metaTitle: string;
  metaDescription: string;
  focusKeyword: string;
  description: string;
  hook: string;
  benefits: string[];
  usage: {
    steps: string[];
    image: string;
  };
  cta: string;
  reviews: ProductReview[];
  relatedProductIds: string[];
  ecommerceLinks: EcommerceLinks;
}

export const products: Product[] = [
  {
    id: "1",
    slug: "asam-amino",
    name: "Asam Amino Dokter Tani",
    category: "Pupuk Organik",
    tags: ["Asam Amino", "Anti Stres", "Booster Buah", "Pupuk Organik Cair"],
    stock: "Tersedia",
    unit: "500 ml",
    image: "/Katalog Dokter Tani/asam-amino/images/asam-amino_01.jpg",
    images: [
      "/Katalog Dokter Tani/asam-amino/images/asam-amino_01.jpg",
      "/Katalog Dokter Tani/asam-amino/images/asam-amino_02.jpg",
      "/Katalog Dokter Tani/asam-amino/images/asam-amino_03.jpg",
      "/Katalog Dokter Tani/asam-amino/images/asam-amino_04.jpg",
      "/Katalog Dokter Tani/asam-amino/images/asam-amino_05.jpg",
    ],
    metaTitle: "Asam Amino Dokter Tani 500ml - Infus Nutrisi Anti-Stres & Booster Buah",
    metaDescription: "Tanaman stres karena pindah tanam atau cuaca ekstrem? Beri infus nutrisi dengan Asam Amino Dokter Tani. Mempercepat pemulihan, melebatkan bunga & buah. Terjual 1.000+ botol!",
    focusKeyword: "Asam Amino Dokter Tani",
    hook: "Tanaman Anda terlihat lesu, kerdil, atau sulit berbuah setelah pindah tanam atau cuaca ekstrem? Itu tandanya tanaman sedang stres! Saat stres, tanaman tidak bisa memproduksi energi.",
    description: "Diformulasikan dari asam amino esensial murni, Asam Amino Dokter Tani bekerja seperti minuman energi bagi tanaman. Beri pertolongan pertama dengan \"infus\" nutrisi instan yang bisa langsung diserap tanpa perlu fotosintesis. Sudah dipercaya oleh ribuan petani di seluruh Indonesia dengan rating 4.9/5.0.",
    benefits: [
      "Pemulihan Cepat: Mengembalikan kesegaran dan pertumbuhan tanaman yang stres",
      "Booster Generatif: Mengoptimalkan pembentukan bunga dan buah, mencegah kerontokan",
      "Peningkat Imunitas: Membuat tanaman lebih tahan terhadap serangan hama dan penyakit",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml Asam Amino Dokter Tani dengan 1 liter air bersih",
        "Semprotkan secara merata ke seluruh bagian tanaman (daun, batang, dan sekitar perakaran)",
        "Aplikasikan setiap 7-14 hari sekali, terutama saat tanaman menunjukkan tanda stres atau memasuki fase generatif",
      ],
      image: "/Katalog Dokter Tani/asam-amino/images/asam-amino_02.jpg",
    },
    cta: "Jangan biarkan tanaman Anda stres berlarut-larut. Sediakan selalu Asam Amino Dokter Tani. Beli Sekarang & Konsultasi Gratis dengan Tim Ahli Kami!",
    reviews: [
      { id: "r1", name: "Pak Budi", rating: 5, date: "2025-12-15", comment: "Tanaman cabai saya yang stres karena cuaca panas langsung segar kembali setelah 3 hari aplikasi. Luar biasa!" },
      { id: "r2", name: "Ibu Sari", rating: 5, date: "2025-11-20", comment: "Bunga mangga saya jadi lebat dan tidak rontok lagi setelah pakai Asam Amino ini. Sangat recommended!" },
      { id: "r3", name: "Mas Agus", rating: 4, date: "2025-11-10", comment: "Produk bagus untuk pemulihan tanaman pasca pindah tanam. Pengiriman cepat." },
    ],
    relatedProductIds: ["10", "31"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "2",
    slug: "bio-magic",
    name: "Bio Magic Dokter Tani (Trichoderma Harzianum)",
    category: "Fungisida Hayati",
    tags: ["Trichoderma", "Fungisida Hayati", "Anti Layu Fusarium", "Busuk Akar"],
    stock: "Tersedia",
    unit: "1 kg",
    image: "/Katalog Dokter Tani/bio-magic/images/bio-magic_01.jpg",
    images: [
      "/Katalog Dokter Tani/bio-magic/images/bio-magic_01.jpg",
      "/Katalog Dokter Tani/bio-magic/images/bio-magic_02.jpg",
      "/Katalog Dokter Tani/bio-magic/images/bio-magic_03.jpg",
      "/Katalog Dokter Tani/bio-magic/images/bio-magic_04.jpg",
      "/Katalog Dokter Tani/bio-magic/images/bio-magic_05.jpg",
    ],
    metaTitle: "Bio Magic Dokter Tani 1kg - Fungisida Hayati Pembasmi Layu Fusarium & Busuk Akar",
    metaDescription: "Tanaman cabai atau sayuran Anda mati mendadak karena layu? Atasi dengan Bio Magic Dokter Tani. Fungisida hayati berbasis Trichoderma Harzianum, terbukti ampuh atasi jamur tanah.",
    focusKeyword: "Bio Magic Dokter Tani",
    hook: "Pernahkah Anda menanam cabai, tomat, atau melon yang tiba-tiba layu seperti tersiram air panas padahal tanahnya basah? Itu adalah serangan Layu Fusarium, jamur ganas yang hidup di dalam tanah dan menyumbat akar.",
    description: "Bio Magic Dokter Tani bukan fungisida kimia, melainkan \"pasukan\" mikroba baik (Trichoderma Harzianum) yang akan melindungi perakaran tanaman Anda. Produk terlaris dengan ribuan ulasan positif. Petani cabai dan hortikultura telah membuktikan keampuhannya. Rating 4.9/5.0 di Shopee & Tokopedia!",
    benefits: [
      "Melawan Patogen: Secara aktif memburu dan mematikan jamur jahat penyebab layu fusarium, busuk akar, dan busuk batang",
      "Membuat Perisai: Membentuk koloni di sekitar akar, menciptakan benteng pertahanan alami",
      "Menyuburkan Tanah: Mengurai bahan organik dan membuat nutrisi lebih tersedia bagi tanaman",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 gram Bio Magic per liter air, aduk hingga larut",
        "Siramkan larutan ke area perakaran tanaman atau campurkan dengan media tanam sebelum tanam",
        "Aplikasikan saat pagi atau sore hari, ulangi setiap 14-21 hari untuk perlindungan optimal",
      ],
      image: "/Katalog Dokter Tani/bio-magic/images/bio-magic_03.jpg",
    },
    cta: "Jangan tunggu tanaman Anda jadi korban. Lindungi dari sekarang! Dapatkan Bio Magic 1kg Sekarang, Stok Terbatas!",
    reviews: [
      { id: "r4", name: "Pak Hendra", rating: 5, date: "2025-12-01", comment: "Layu fusarium pada cabai saya berhenti menyebar setelah 2 minggu aplikasi Bio Magic. Luar biasa!" },
      { id: "r5", name: "Ibu Dewi", rating: 5, date: "2025-11-25", comment: "Tanaman tomat saya yang busuk akar akhirnya bisa diselamatkan. Terima kasih Dokter Tani!" },
      { id: "r6", name: "Mas Rudi", rating: 4, date: "2025-11-10", comment: "Produk bagus. Tanah jadi lebih gembur dan tanaman lebih sehat." },
    ],
    relatedProductIds: ["3", "4", "15"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "3",
    slug: "black-turbo",
    name: "Black Turbo Dokter Tani (Asam Humat)",
    category: "Pembenah Tanah",
    tags: ["Asam Humat", "Pembenah Tanah", "Penyubur Tanah", "Tanah Keras"],
    stock: "Tersedia",
    unit: "1 kg",
    image: "/Katalog Dokter Tani/black-turbo/images/black-turbo_01.jpg",
    images: [
      "/Katalog Dokter Tani/black-turbo/images/black-turbo_01.jpg",
      "/Katalog Dokter Tani/black-turbo/images/black-turbo_02.jpg",
      "/Katalog Dokter Tani/black-turbo/images/black-turbo_03.jpg",
      "/Katalog Dokter Tani/black-turbo/images/black-turbo_04.jpg",
      "/Katalog Dokter Tani/black-turbo/images/black-turbo_05.jpg",
    ],
    metaTitle: "Black Turbo Asam Humat 1kg - Pembenah Tanah Ajaib, Solusi Tanah Keras & Bantat",
    metaDescription: "Pupuk kimia bikin tanah jadi keras dan tidak subur? Gemburkan kembali dengan Black Turbo Dokter Tani. Asam humat murni yang terbukti memperbaiki struktur tanah dan memaksimalkan penyerapan pupuk.",
    focusKeyword: "Black Turbo Dokter Tani",
    hook: "Merasa pemupukan semakin boros tapi hasil panen tidak meningkat? Tanah di lahan Anda terasa keras saat dicangkul? Itu tandanya tanah Anda sudah jenuh dan miskin bahan organik.",
    description: "Black Turbo Dokter Tani bukan pupuk biasa, melainkan \"vitamin\" untuk tanah. Mengandung Asam Humat murni, Black Turbo bekerja menggemburkan tanah, mengikat pupuk agar tidak tercuci, dan menetralkan pH. Produk Star+ dengan ratusan testimoni positif!",
    benefits: [
      "Menggemburkan Tanah: Memecah partikel tanah yang padat, menciptakan rongga udara dan air agar akar leluasa bergerak",
      "Mengikat Pupuk: Meningkatkan Kapasitas Tukar Kation (KTK), sehingga pupuk tidak mudah tercuci air hujan dan siap diserap akar",
      "Menetralkan pH: Menstabilkan pH tanah yang terlalu asam akibat pupuk kimia",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 gram Black Turbo per liter air, atau taburkan langsung ke tanah 50-100 gram per tanaman",
        "Aplikasikan pada tanah di sekitar perakaran tanaman, lalu siram dengan air secukupnya",
        "Gunakan setiap 30 hari sekali untuk menjaga kesuburan tanah secara berkelanjutan",
      ],
      image: "/Katalog Dokter Tani/black-turbo/images/black-turbo_03.jpg",
    },
    cta: "Berhenti membuang uang untuk pupuk yang tidak terserap. Sehatkan dulu tanahnya! Pesan Black Turbo Sekarang dan Dapatkan Layanan Konsultasi Tanah Gratis!",
    reviews: [
      { id: "r7", name: "Pak Joko", rating: 5, date: "2025-12-10", comment: "Tanah sawah saya yang keras jadi gembur dalam 2 minggu. Akar padi tumbuh lebih dalam dan kuat!" },
      { id: "r8", name: "Ibu Ani", rating: 5, date: "2025-11-28", comment: "Pupuk jadi lebih efektif setelah pakai Black Turbo. Hemat biaya pemupukan sampai 30%." },
      { id: "r9", name: "Mas Dani", rating: 4, date: "2025-11-15", comment: "Produk mantap untuk tanah yang sudah jenuh pupuk kimia." },
    ],
    relatedProductIds: ["14", "32", "1"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "4",
    slug: "kalium-silikat",
    name: "Kalium Silikat Dokter Tani",
    category: "Pupuk Khusus",
    tags: ["Kalium Silikat", "Anti Rebah", "Penguat Batang", "Pupuk Padi"],
    stock: "Tersedia",
    unit: "1 kg",
    image: "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_01.jpg",
    images: [
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_01.jpg",
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_02.jpg",
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_03.jpg",
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_04.jpg",
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_05.jpg",
    ],
    metaTitle: "Kalium Silikat Dokter Tani - Pupuk Anti Rebah & Penguat Batang Padi",
    metaDescription: "Khawatir padi Anda roboh saat musim hujan dan angin kencang? Perkuat batangnya dengan Kalium Silikat dari Dokter Tani. Terbukti membuat batang lebih kokoh, tegak, dan tahan hama.",
    focusKeyword: "Kalium Silikat Dokter Tani",
    hook: "Pemandangan paling menyedihkan bagi petani padi adalah saat bulir mulai menguning, tapi tanaman justru roboh (rebah) diterpa angin dan hujan. Hasil panen bisa anjlok hingga 50%!",
    description: "Berikan \"tulang\" yang kuat untuk tanaman padi Anda dengan Kalium Silikat Dokter Tani. Pupuk ini bekerja seperti suplemen kalsium bagi manusia. Silika akan melapisi dinding sel batang, membuatnya lebih tebal, kaku, dan kokoh. Jadi andalan petani di musim penghujan.",
    benefits: [
      "Mempertebal Dinding Sel: Silika melapisi dinding sel batang, membuatnya lebih tebal, kaku, dan kokoh",
      "Mencegah Hama: Lapisan silika yang keras membuat hama penggerek batang dan penghisap sulit menembus jaringan tanaman",
      "Meningkatkan Fotosintesis: Daun menjadi lebih tegak, memaksimalkan penangkapan cahaya matahari",
    ],
    usage: {
      steps: [
        "Larutkan 2-5 gram Kalium Silikat per liter air",
        "Semprotkan ke seluruh bagian tanaman atau siramkan ke area perakaran",
        "Aplikasikan setiap 10-14 hari sekali, terutama pada fase anakan aktif hingga pengisian bulir",
      ],
      image: "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_03.jpg",
    },
    cta: "Amankan hasil panen Anda dari ancaman padi rebah. Beli Kalium Silikat Sekarang, Mumpung Stok Masih Ada!",
    reviews: [
      { id: "r10", name: "Pak Warto", rating: 5, date: "2025-12-05", comment: "Padi saya tidak rebah lagi di musim hujan. Batang kokoh dan bulir bernas. Kalium Silikat memang jempolan!" },
      { id: "r11", name: "Mas Teguh", rating: 5, date: "2025-11-22", comment: "Dulu rugi besar karena padi rebah. Sekarang aman pakai Kalium Silikat Dokter Tani." },
      { id: "r12", name: "Ibu Yuli", rating: 4, date: "2025-11-08", comment: "Bagus untuk perkuat batang. Tanaman jadi tegak dan sehat." },
    ],
    relatedProductIds: ["11", "18", "28"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "5",
    slug: "bio-magic-jar",
    name: "Bio Magic Jar Dokter Tani",
    category: "Fungisida Hayati",
    tags: ["Trichoderma", "Fungisida Hayati", "Kemasan Ekonomis", "Lahan Luas"],
    stock: "Tersedia",
    unit: "1 kg",
    image: "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_01.jpg",
    images: [
      "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_01.jpg",
      "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_02.jpg",
      "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_03.jpg",
      "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_04.jpg",
      "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_05.jpg",
    ],
    metaTitle: "Bio Magic Jar Dokter Tani 1kg - Fungisida Hayati Trichoderma Ekonomis",
    metaDescription: "Butuh perlindungan jamur tanah skala besar? Bio Magic Jar Dokter Tani solusinya! Trichoderma Harzianum ampuh atasi layu fusarium & busuk akar. Kemasan hemat!",
    focusKeyword: "Bio Magic Jar Dokter Tani",
    hook: "Untuk Anda para petani yang mengelola lahan luas atau membutuhkan solusi anti-jamur dalam jumlah besar, masalah layu fusarium dan busuk akar bisa menjadi ancaman serius yang menguras biaya dan tenaga.",
    description: "Bio Magic Jar Dokter Tani adalah jawaban ekonomis dan efektif. Dalam kemasan jar 1kg yang lebih hemat, Anda mendapatkan konsentrasi tinggi mikroba baik Trichoderma Harzianum yang siap melindungi tanaman Anda. Pilihan cerdas para petani profesional.",
    benefits: [
      "Perlindungan Skala Besar: Ideal untuk aplikasi di lahan yang lebih luas, menghemat biaya per unit",
      "Basmi Jamur Ganas: Efektif menekan dan membasmi jamur patogen penyebab layu fusarium, busuk akar, dan busuk batang",
      "Tanah Sehat, Tanaman Kuat: Memperbaiki ekosistem mikroba tanah, menjadikan tanaman lebih tahan penyakit secara alami",
    ],
    usage: {
      steps: [
        "Campurkan 10-20 gram Bio Magic Jar per liter air",
        "Siramkan ke area perakaran atau campurkan dengan pupuk kandang sebelum aplikasi",
        "Gunakan setiap 14-21 hari untuk perlindungan berkelanjutan",
      ],
      image: "/Katalog Dokter Tani/bio-magic-jar/images/bio-magic-jar_03.jpg",
    },
    cta: "Lindungi investasi pertanian Anda dengan solusi anti-jamur yang hemat dan ampuh. Pesan Bio Magic Jar Dokter Tani Sekarang untuk Panen Lebih Aman!",
    reviews: [
      { id: "r13", name: "Pak Slamet", rating: 5, date: "2025-12-08", comment: "Kemasan jar lebih hemat untuk lahan 2 hektar saya. Hasilnya sama ampuhnya!" },
      { id: "r14", name: "Mas Eko", rating: 5, date: "2025-11-18", comment: "Bio Magic Jar cocok untuk petani profesional. Hemat dan efektif." },
    ],
    relatedProductIds: ["2", "6", "15"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "6",
    slug: "bio-magic-pouch",
    name: "Bio Magic Pouch Dokter Tani",
    category: "Fungisida Hayati",
    tags: ["Trichoderma", "Fungisida Hayati", "Kebun Rumah", "Praktis"],
    stock: "Tersedia",
    unit: "250 g",
    image: "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_01.jpg",
    images: [
      "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_01.jpg",
      "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_02.jpg",
      "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_03.jpg",
      "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_04.jpg",
      "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_05.jpg",
    ],
    metaTitle: "Bio Magic Pouch Dokter Tani - Fungisida Hayati Praktis untuk Kebun Rumah",
    metaDescription: "Atasi jamur tanah di kebun rumah atau tanaman hias Anda dengan Bio Magic Pouch Dokter Tani. Fungisida hayati Trichoderma dalam kemasan praktis, mudah digunakan, dan aman.",
    focusKeyword: "Bio Magic Pouch Dokter Tani",
    hook: "Tanaman hias kesayangan Anda tiba-tiba layu atau busuk akarnya? Atau sayuran di kebun rumah Anda sering terserang jamur? Masalah jamur tanah bisa sangat menjengkelkan.",
    description: "Bio Magic Pouch Dokter Tani hadir sebagai solusi anti-jamur yang ringkas dan mudah digunakan. Dengan kandungan mikroba Trichoderma Harzianum yang ampuh, produk ini melindungi tanaman dari berbagai penyakit jamur tanah. Direkomendasikan oleh para pegiat hobi tanaman.",
    benefits: [
      "Praktis & Mudah: Dosis yang pas untuk aplikasi skala kecil, tidak perlu repot menakar",
      "Aman & Organik: Melindungi tanaman tanpa residu kimia berbahaya, aman untuk keluarga dan hewan peliharaan",
      "Tanaman Sehat & Indah: Mengembalikan kesehatan tanah dan memperkuat daya tahan alami tanaman hias maupun sayuran",
    ],
    usage: {
      steps: [
        "Campurkan 5 gram Bio Magic Pouch per liter air",
        "Siramkan ke area perakaran tanaman hias atau sayuran di pot/polybag",
        "Aplikasikan setiap 14 hari untuk perlindungan berkelanjutan",
      ],
      image: "/Katalog Dokter Tani/bio-magic-pouch/images/bio-magic-pouch_03.jpg",
    },
    cta: "Jangan biarkan jamur merusak keindahan tanaman Anda. Dapatkan Bio Magic Pouch Dokter Tani Sekarang & Nikmati Kebun Sehat Bebas Jamur!",
    reviews: [
      { id: "r15", name: "Ibu Rina", rating: 5, date: "2025-12-03", comment: "Tanaman hias saya yang busuk akar akhirnya pulih. Kemasan pouch sangat praktis!" },
      { id: "r16", name: "Mas Yoga", rating: 4, date: "2025-11-20", comment: "Cocok untuk kebun rumah. Mudah dipakai dan hasilnya nyata." },
    ],
    relatedProductIds: ["2", "5", "20"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "7",
    slug: "booster-anggur",
    name: "Booster Anggur Dokter Tani",
    category: "Booster Buah",
    tags: ["Booster Anggur", "Perangsang Buah", "Anti Rontok", "Pupuk Organik"],
    stock: "Tersedia",
    unit: "250 ml",
    image: "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_01.jpg",
    images: [
      "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_01.jpg",
      "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_02.jpg",
      "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_03.jpg",
      "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_04.jpg",
      "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_05.jpg",
    ],
    metaTitle: "Booster Anggur Dokter Tani - Pupuk Organik Perangsang Buah Anggur Manis & Lebat",
    metaDescription: "Ingin panen anggur lebat, manis, dan anti rontok? Booster Anggur Dokter Tani solusinya! Pupuk organik cair ini merangsang pembuahan serempak & tingkatkan kualitas buah.",
    focusKeyword: "Booster Anggur Dokter Tani",
    hook: "Sudah merawat pohon anggur dengan sepenuh hati, tapi buahnya sedikit, kecil, atau sering rontok sebelum matang? Impian panen anggur manis dan lebat di halaman rumah seringkali terhambat masalah ini.",
    description: "Wujudkan panen anggur impian Anda dengan Booster Anggur Pouch Dokter Tani! Formula organik cair ini dirancang khusus untuk memicu dan memaksimalkan potensi buah anggur Anda. Kandungan hormon GA3, Auksin, dan Sitokinin alami bekerja sinergis.",
    benefits: [
      "Pembuahan Serempak: Merangsang pembentukan bunga dan buah secara massal dan seragam",
      "Kualitas Buah Premium: Meningkatkan ukuran, warna, dan kadar gula, menghasilkan anggur yang lebih manis",
      "Anti Rontok: Memperkuat tangkai buah, mencegah kerontokan dini akibat stres atau kekurangan nutrisi",
    ],
    usage: {
      steps: [
        "Campurkan 5 ml Booster Anggur per liter air",
        "Semprotkan ke seluruh bagian tanaman anggur, terutama saat fase pembungaan dan pembuahan",
        "Ulangi setiap 7-10 hari untuk hasil yang optimal",
      ],
      image: "/Katalog Dokter Tani/booster-anggur-pouch/images/booster-anggur-pouch_03.jpg",
    },
    cta: "Jangan tunda lagi panen anggur manis Anda. Beli Booster Anggur Pouch Dokter Tani Sekarang & Rasakan Bedanya!",
    reviews: [
      { id: "r17", name: "Pak Herman", rating: 5, date: "2025-12-12", comment: "Anggur saya berbuah lebat dan manis banget! Booster ini memang juara." },
      { id: "r18", name: "Ibu Maya", rating: 5, date: "2025-11-30", comment: "Buah anggur tidak rontok lagi. Ukurannya juga lebih besar dari biasanya." },
    ],
    relatedProductIds: ["8", "9", "31"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "8",
    slug: "booster-kelengkeng",
    name: "Booster Kelengkeng Dokter Tani",
    category: "Booster Buah",
    tags: ["Booster Kelengkeng", "Pemicu Buah", "Di Luar Musim", "Pupuk Organik"],
    stock: "Tersedia",
    unit: "250 ml",
    image: "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_01.jpg",
    images: [
      "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_01.jpg",
      "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_02.jpg",
      "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_03.jpg",
      "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_04.jpg",
      "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_05.jpg",
    ],
    metaTitle: "Booster Kelengkeng Dokter Tani - Pupuk Organik Pemicu Buah Kelengkeng di Luar Musim",
    metaDescription: "Panen kelengkeng di luar musim bukan lagi mimpi! Booster Kelengkeng Dokter Tani merangsang pembungaan & pembuahan serempak, hasilkan buah lebat & manis.",
    focusKeyword: "Booster Kelengkeng Dokter Tani",
    hook: "Pernahkah Anda iri melihat tetangga panen kelengkeng di luar musim, sementara pohon Anda hanya berdaun lebat? Membuahkan kelengkeng di luar musim seringkali dianggap sulit, padahal ada rahasianya!",
    description: "Rahasianya adalah Booster Kelengkeng Pouch Dokter Tani! Pupuk organik cair ini diformulasikan khusus untuk memanipulasi hormon tanaman kelengkeng, memicu pembungaan dan pembuahan di waktu yang Anda inginkan.",
    benefits: [
      "Pemicu Pembuahan: Merangsang tunas generatif untuk menghasilkan bunga dan buah secara serempak",
      "Panen di Luar Musim: Memungkinkan Anda menikmati buah kelengkeng segar saat harga sedang tinggi",
      "Kualitas Buah Optimal: Menghasilkan buah yang banyak, berukuran seragam, dan memiliki rasa manis yang khas",
    ],
    usage: {
      steps: [
        "Campurkan 5 ml Booster Kelengkeng per liter air",
        "Semprotkan ke seluruh bagian tanaman kelengkeng saat fase induksi pembungaan",
        "Ulangi setiap 7-10 hari, lakukan 3-4 kali penyemprotan berturut-turut",
      ],
      image: "/Katalog Dokter Tani/booster-kelengkeng-pouch/images/booster-kelengkeng-pouch_03.jpg",
    },
    cta: "Jadilah yang pertama panen kelengkeng di luar musim. Pesan Booster Kelengkeng Pouch Dokter Tani Sekarang & Raih Keuntungan Lebih!",
    reviews: [
      { id: "r19", name: "Pak Sutomo", rating: 5, date: "2025-12-07", comment: "Pohon kelengkeng saya berbuah di luar musim! Harga jual tinggi, untung berlipat!" },
      { id: "r20", name: "Ibu Endang", rating: 5, date: "2025-11-25", comment: "Luar biasa! Kelengkeng berbuah lebat padahal bukan musimnya." },
    ],
    relatedProductIds: ["7", "9", "31"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "9",
    slug: "booster-mangga",
    name: "Booster Mangga Dokter Tani",
    category: "Booster Buah",
    tags: ["Booster Mangga", "Perangsang Buah", "Mangga Besar", "Pupuk Organik"],
    stock: "Tersedia",
    unit: "250 ml",
    image: "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_01.jpg",
    images: [
      "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_01.jpg",
      "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_02.jpg",
      "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_03.jpg",
      "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_04.jpg",
      "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_05.jpg",
    ],
    metaTitle: "Booster Mangga Dokter Tani - Pupuk Organik Perangsang Buah Mangga Besar & Manis",
    metaDescription: "Ingin mangga Anda berbuah lebat, besar, dan manis? Booster Mangga Dokter Tani adalah solusi pupuk organik cair untuk optimalkan pembuahan & kualitas buah mangga.",
    focusKeyword: "Booster Mangga Dokter Tani",
    hook: "Pohon mangga Anda sudah besar tapi buahnya jarang, kecil, atau rasanya kurang manis? Atau buahnya sering rontok sebelum sempat matang? Jangan biarkan potensi pohon mangga Anda terbuang sia-sia!",
    description: "Maksimalkan potensi panen mangga Anda dengan Booster Mangga Pouch Dokter Tani! Pupuk organik cair ini dirancang khusus untuk merangsang pembungaan dan pembuahan pada tanaman mangga. Produk favorit para pecinta mangga.",
    benefits: [
      "Memicu Buah Lebat: Merangsang pembentukan buah yang lebih banyak dan serempak",
      "Kualitas Buah Unggul: Menghasilkan buah berukuran besar, daging tebal, dan rasa manis yang khas",
      "Tahan Rontok: Meningkatkan ketahanan tanaman terhadap stres lingkungan dan mencegah kerontokan buah prematur",
    ],
    usage: {
      steps: [
        "Campurkan 5 ml Booster Mangga per liter air",
        "Semprotkan ke seluruh bagian tanaman mangga, terutama saat tunas bunga mulai muncul",
        "Ulangi penyemprotan setiap 7-10 hari selama fase pembungaan dan pembuahan",
      ],
      image: "/Katalog Dokter Tani/booster-mangga-pouch/images/booster-mangga-pouch_03.jpg",
    },
    cta: "Dapatkan panen mangga terbaik Anda tahun ini. Beli Booster Mangga Pouch Dokter Tani Sekarang & Nikmati Mangga Kualitas Premium!",
    reviews: [
      { id: "r21", name: "Pak Bambang", rating: 5, date: "2025-12-09", comment: "Mangga harum manis saya buahnya jumbo-jumbo! Booster ini memang top." },
      { id: "r22", name: "Ibu Wati", rating: 5, date: "2025-11-22", comment: "Pohon yang biasanya jarang berbuah, sekarang lebat luar biasa." },
    ],
    relatedProductIds: ["7", "8", "31"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "10",
    slug: "bundling-cabai",
    name: "Bundling Cabai Dokter Tani",
    category: "Paket Bundling",
    tags: ["Bundling Cabai", "Paket Pupuk", "Anti Patek", "Panen Melimpah"],
    stock: "Tersedia",
    unit: "1 paket",
    image: "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_01.jpg",
    images: [
      "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_01.jpg",
      "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_02.jpg",
      "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_03.jpg",
      "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_04.jpg",
      "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_05.jpg",
    ],
    metaTitle: "Bundling Cabai Dokter Tani - Paket Pupuk Lengkap Anti Patek & Panen Melimpah",
    metaDescription: "Sukseskan budidaya cabai Anda dengan Bundling Cabai Dokter Tani! Paket lengkap POC, fungisida, & asam amino untuk pertumbuhan optimal, anti patek, & hasil panen melimpah.",
    focusKeyword: "Bundling Cabai Dokter Tani",
    hook: "Budidaya cabai seringkali penuh tantangan: mulai dari serangan patek (antraknosa), layu fusarium, hingga bunga dan buah yang rontok. Jika tidak ditangani dengan tepat, modal bisa habis, panen pun gagal total.",
    description: "Bundling Cabai Dokter Tani adalah solusi terpadu. Paket lengkap berisi POC Cabai untuk nutrisi optimal, PHC Fungisida untuk perlindungan patek, dan Asam Amino untuk pemulihan stres. Ribuan petani cabai telah membuktikan efektivitasnya!",
    benefits: [
      "POC Cabai: Nutrisi spesifik untuk pertumbuhan vegetatif dan generatif optimal, memperbanyak bunga dan buah",
      "PHC Fungisida: Perlindungan ampuh dari serangan patek (antraknosa) dan jamur lainnya",
      "Asam Amino: Memulihkan tanaman dari stres, meningkatkan imunitas pasca serangan hama/penyakit",
    ],
    usage: {
      steps: [
        "Aplikasikan POC Cabai setiap 7-14 hari dengan dosis 5-10 ml per liter air",
        "Semprotkan PHC Fungisida setiap 7-10 hari untuk pencegahan patek",
        "Berikan Asam Amino saat tanaman terlihat stres atau setelah cuaca ekstrem",
      ],
      image: "/Katalog Dokter Tani/bundling-cabai/images/bundling-cabai_03.jpg",
    },
    cta: "Wujudkan panen cabai impian Anda yang lebat dan bebas penyakit. Dapatkan Bundling Cabai Dokter Tani Sekarang & Raih Keuntungan Maksimal!",
    reviews: [
      { id: "r23", name: "Pak Supriyadi", rating: 5, date: "2025-12-14", comment: "Paket bundling ini lengkap banget! Cabai saya panen melimpah dan bebas patek." },
      { id: "r24", name: "Mas Irwan", rating: 5, date: "2025-11-28", comment: "Investasi terbaik untuk petani cabai. Satu paket solusi semua masalah." },
    ],
    relatedProductIds: ["23", "1", "15"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "11",
    slug: "bundling-padi",
    name: "Bundling Padi Dokter Tani",
    category: "Paket Bundling",
    tags: ["Bundling Padi", "Paket Pupuk Padi", "Anti Rebah", "Anti Kresek"],
    stock: "Tersedia",
    unit: "1 paket",
    image: "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_01.jpg",
    images: [
      "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_01.jpg",
      "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_02.jpg",
      "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_03.jpg",
      "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_04.jpg",
      "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_05.jpg",
    ],
    metaTitle: "Bundling Padi Dokter Tani - Paket Pupuk Padi Anti Rebah, Bernas & Bebas Kresek",
    metaDescription: "Tingkatkan produktivitas padi Anda dengan Bundling Padi Dokter Tani! Paket POC, Kalium Silikat, & Bakterisida untuk padi bernas, batang kuat anti rebah, & tahan penyakit kresek.",
    focusKeyword: "Bundling Padi Dokter Tani",
    hook: "Padi rebah, serangan kresek, atau anakan yang sedikit adalah mimpi buruk bagi setiap petani padi. Hasil panen bisa anjlok drastis, bahkan gagal total.",
    description: "Bundling Padi Dokter Tani adalah jawaban komprehensif. Paket lengkap POC Padi untuk anakan produktif, Kalium Silikat untuk batang kokoh, dan PHC Bakterisida untuk anti kresek. Andalan petani padi modern!",
    benefits: [
      "POC Padi: Merangsang anakan produktif lebih banyak dan memastikan pengisian bulir bernas sempurna",
      "Kalium Silikat: Memperkuat batang padi agar kokoh, tegak, dan anti rebah akibat angin atau beban bulir",
      "PHC Bakterisida: Melindungi dari penyakit kresek (hawar daun bakteri) yang mematikan",
    ],
    usage: {
      steps: [
        "Aplikasikan POC Padi sejak fase anakan aktif, 5-10 ml per liter air setiap 7-14 hari",
        "Berikan Kalium Silikat pada fase anakan aktif hingga pengisian bulir",
        "Semprotkan PHC Bakterisida saat gejala kresek mulai muncul atau sebagai pencegahan",
      ],
      image: "/Katalog Dokter Tani/bundling-padi/images/bundling-padi_03.jpg",
    },
    cta: "Raih panen padi terbaik Anda tahun ini. Beli Bundling Padi Dokter Tani Sekarang & Amankan Hasil Panen Anda!",
    reviews: [
      { id: "r25", name: "Pak Darmo", rating: 5, date: "2025-12-11", comment: "Padi saya tidak rebah dan bebas kresek! Bundling ini wajib punya tiap musim tanam." },
      { id: "r26", name: "Ibu Sumiyati", rating: 5, date: "2025-11-20", comment: "Hasil panen meningkat 30% setelah pakai bundling ini. Mantap!" },
    ],
    relatedProductIds: ["4", "18", "28"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "12",
    slug: "kalium-silikat-kemasan",
    name: "Kalium Silikat Dokter Tani (Multi Kemasan)",
    category: "Pupuk Khusus",
    tags: ["Kalium Silikat", "Anti Rebah", "Penguat Batang", "Multi Kemasan"],
    stock: "Tersedia",
    unit: "50g / 1kg",
    image: "/Katalog Dokter Tani/kalium-silikat/1000/kalium-silikat_01.jpg",
    images: [
      "/Katalog Dokter Tani/kalium-silikat/1000/kalium-silikat_01.jpg",
      "/Katalog Dokter Tani/kalium-silikat/1000/kalium-silikat_02.jpg",
      "/Katalog Dokter Tani/kalium-silikat/1000/kalium-silikat_03.jpg",
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_04.jpg",
      "/Katalog Dokter Tani/kalium-silikat/50/kalium-silikat_05.jpg",
    ],
    metaTitle: "Kalium Silikat Dokter Tani - Pupuk Anti Rebah Padi & Penguat Batang Tanaman",
    metaDescription: "Khawatir padi roboh atau tanaman lain mudah patah? Kalium Silikat Dokter Tani solusinya! Pupuk organik ini perkuat batang, tingkatkan ketahanan hama, & optimalkan hasil panen.",
    focusKeyword: "Kalium Silikat Dokter Tani",
    hook: "Musim hujan dan angin kencang seringkali menjadi momok bagi petani. Tanaman padi yang sudah berbuah lebat bisa roboh (rebah) dalam semalam, menyebabkan kerugian besar.",
    description: "Berikan perlindungan ekstra dengan Kalium Silikat Dokter Tani. Pupuk organik ini membentuk lapisan silika pada dinding sel batang tanaman, menjadikannya lebih kuat dan tangguh. Terbukti mengurangi tingkat rebah hingga 80%!",
    benefits: [
      "Batang Kokoh Anti Rebah: Padi dan tanaman lain akan lebih tegak, tahan terhadap angin kencang dan beban buah",
      "Perisai Hama Alami: Lapisan silika menyulitkan hama penghisap dan penggerek untuk menyerang",
      "Meningkatkan Kualitas: Tanaman lebih sehat, fotosintesis optimal, menghasilkan panen yang lebih baik",
    ],
    usage: {
      steps: [
        "Larutkan 2-5 gram Kalium Silikat per liter air",
        "Semprotkan ke seluruh bagian tanaman atau siramkan ke area perakaran",
        "Gunakan setiap 10-14 hari untuk perlindungan berkelanjutan",
      ],
      image: "/Katalog Dokter Tani/kalium-silikat/1000/kalium-silikat_03.jpg",
    },
    cta: "Jangan biarkan tanaman Anda roboh begitu saja. Dapatkan Kalium Silikat Dokter Tani Hari Ini & Panen Lebih Aman!",
    reviews: [
      { id: "r27", name: "Pak Mulyono", rating: 5, date: "2025-12-06", comment: "Kemasan 1kg sangat hemat untuk lahan luas saya. Padi anti rebah!" },
      { id: "r28", name: "Mas Aji", rating: 4, date: "2025-11-15", comment: "Produk wajib punya di musim hujan." },
    ],
    relatedProductIds: ["4", "11", "18"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "13",
    slug: "phc-bakterisida",
    name: "PHC Bakterisida Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["Bakterisida", "Anti Bakteri", "Layu Bakteri", "Hawar Daun"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/phc-bakterisida/500/phc-bakterisida-1L_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-bakterisida/500/phc-bakterisida-1L_01.jpg",
      "/Katalog Dokter Tani/phc-bakterisida/500/phc-bakterisida-1L_02.jpg",
      "/Katalog Dokter Tani/phc-bakterisida/500/phc-bakterisida-1L_03.jpg",
      "/Katalog Dokter Tani/phc-bakterisida/250/phc-bakterisida-1L_04.jpg",
      "/Katalog Dokter Tani/phc-bakterisida/250/phc-bakterisida-1L_05.jpg",
    ],
    metaTitle: "PHC Bakterisida Dokter Tani - Pembasmi Bakteri Patogen Layu & Hawar Daun Organik",
    metaDescription: "Tanaman layu mendadak atau daun mengering karena bakteri? PHC Bakterisida Dokter Tani adalah solusi organik untuk atasi layu bakteri & hawar daun. Aman & efektif.",
    focusKeyword: "PHC Bakterisida Dokter Tani",
    hook: "Penyakit layu bakteri dan hawar daun bisa menyebar dengan cepat dan mematikan tanaman dalam hitungan hari. Gejalanya mirip jamur, tapi penanganannya berbeda. Jangan sampai salah obat!",
    description: "PHC Bakterisida Dokter Tani adalah jawaban spesifik untuk masalah bakteri patogen. Dengan formulasi mikroba antagonis pilihan, produk ini bekerja secara alami untuk membasmi bakteri dan memperkuat sistem imun tanaman.",
    benefits: [
      "Basmi Bakteri Jahat: Menekan pertumbuhan dan membasmi bakteri penyebab layu dan hawar daun",
      "Perlindungan Alami: Menciptakan lingkungan mikroba seimbang di sekitar perakaran, memperkuat sistem imun tanaman",
      "Aman & Ramah Lingkungan: Tanpa residu kimia berbahaya, aman untuk tanaman, petani, dan lingkungan",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml PHC Bakterisida per liter air",
        "Semprotkan ke seluruh bagian tanaman yang terserang atau sebagai pencegahan",
        "Aplikasikan setiap 7-10 hari untuk hasil optimal",
      ],
      image: "/Katalog Dokter Tani/phc-bakterisida/500/phc-bakterisida-1L_03.jpg",
    },
    cta: "Lindungi tanaman Anda dari ancaman bakteri mematikan. Pesan PHC Bakterisida Dokter Tani Sekarang & Jaga Tanaman Tetap Sehat!",
    reviews: [
      { id: "r29", name: "Pak Suyanto", rating: 5, date: "2025-12-04", comment: "Kresek di sawah saya langsung terkendali setelah 2x aplikasi. Top markotop!" },
      { id: "r30", name: "Ibu Titik", rating: 5, date: "2025-11-18", comment: "Layu bakteri pada tomat saya berhenti menyebar. Sangat efektif!" },
    ],
    relatedProductIds: ["15", "18", "20"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "14",
    slug: "phc-dekomposer",
    name: "PHC Dekomposer Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["Dekomposer", "Pengurai Jerami", "Kompos", "Kesuburan Tanah"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/phc-dekomposer/500/phc-dekomposer-1L_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-dekomposer/500/phc-dekomposer-1L_01.jpg",
      "/Katalog Dokter Tani/phc-dekomposer/500/phc-dekomposer-1L_02.jpg",
      "/Katalog Dokter Tani/phc-dekomposer/500/phc-dekomposer-1L_03.jpg",
      "/Katalog Dokter Tani/phc-dekomposer/250/phc-dekomposer-1L_04.jpg",
      "/Katalog Dokter Tani/phc-dekomposer/250/phc-dekomposer-1L_05.jpg",
    ],
    metaTitle: "PHC Dekomposer Dokter Tani - Pupuk Organik Percepat Pengurai Jerami & Kompos",
    metaDescription: "Sulit mengurai jerami atau sisa tanaman? PHC Dekomposer Dokter Tani solusinya! Konsorsium mikroba ini ubah limbah pertanian jadi pupuk alami super cepat.",
    focusKeyword: "PHC Dekomposer Dokter Tani",
    hook: "Setelah panen, jerami dan sisa tanaman seringkali menumpuk di lahan, menjadi sarang hama atau justru dibakar. Padahal, ini adalah \"emas hijau\" yang bisa mengembalikan kesuburan tanah Anda.",
    description: "PHC Dekomposer Dokter Tani adalah kunci untuk mengubah limbah pertanian menjadi berkah. Mengandung konsorsium mikroba perombak bahan organik yang sangat aktif, bekerja super cepat mengurai jerami menjadi kompos kaya nutrisi.",
    benefits: [
      "Dekomposisi Super Cepat: Mempercepat penguraian jerami, kotoran ternak, dan sisa tanaman menjadi kompos dalam waktu singkat",
      "Tingkatkan Kesuburan Tanah: Mengembalikan bahan organik ke tanah, memperbaiki struktur, dan menyediakan nutrisi berkelanjutan",
      "Kurangi Hama & Penyakit: Lingkungan tanah yang sehat akan mengurangi populasi hama dan penyakit",
    ],
    usage: {
      steps: [
        "Campurkan 10-20 ml PHC Dekomposer per liter air",
        "Siramkan secara merata ke tumpukan jerami atau sisa tanaman",
        "Tutup tumpukan dan jaga kelembaban. Kompos siap dalam 14-21 hari",
      ],
      image: "/Katalog Dokter Tani/phc-dekomposer/500/phc-dekomposer-1L_03.jpg",
    },
    cta: "Ubah limbah jadi berkah, sehatkan tanah Anda. Dapatkan PHC Dekomposer Dokter Tani Sekarang & Rasakan Manfaatnya!",
    reviews: [
      { id: "r31", name: "Pak Karno", rating: 5, date: "2025-12-10", comment: "Jerami terurai sempurna dalam 2 minggu! Hemat biaya pupuk kimia." },
      { id: "r32", name: "Mas Didik", rating: 5, date: "2025-11-28", comment: "Kompos dari PHC Dekomposer bikin tanah jadi super subur." },
    ],
    relatedProductIds: ["3", "20", "32"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "15",
    slug: "phc-fungisida",
    name: "PHC Fungisida Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["Fungisida", "Anti Jamur", "Blas", "Patek", "Antraknosa"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/phc-fungisida/500/phc-fungisida-1L_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-fungisida/500/phc-fungisida-1L_01.jpg",
      "/Katalog Dokter Tani/phc-fungisida/500/phc-fungisida-1L_02.jpg",
      "/Katalog Dokter Tani/phc-fungisida/500/phc-fungisida-1L_03.jpg",
      "/Katalog Dokter Tani/phc-fungisida/_DSF1532.JPG",
      "/Katalog Dokter Tani/phc-fungisida/_DSF1537.JPG",
    ],
    metaTitle: "PHC Fungisida Dokter Tani - Pembasmi Jamur Tanaman Organik Anti Blas, Patek & Busuk",
    metaDescription: "Tanaman terserang blas, patek, atau busuk batang? PHC Fungisida Dokter Tani adalah agen hayati ampuh untuk lindungi tanaman dari jamur patogen secara alami.",
    focusKeyword: "PHC Fungisida Dokter Tani",
    hook: "Penyakit jamur seperti blas pada padi, patek (antraknosa) pada cabai, atau busuk batang pada tanaman hortikultura adalah ancaman serius yang bisa menggagalkan panen Anda.",
    description: "PHC Fungisida Dokter Tani mengandung agen hayati pilihan (Trichoderma dan Gliocladium) yang bekerja cerdas. Solusi favorit petani yang peduli lingkungan dan kesehatan. Rating 4.9/5.0 dan telah menyelamatkan ribuan hektar lahan!",
    benefits: [
      "Basmi Jamur Patogen: Secara aktif melawan dan menekan pertumbuhan jamur penyebab penyakit",
      "Perlindungan Menyeluruh: Membentuk perisai biologis di sekitar tanaman, dari akar hingga daun",
      "Aman & Berkelanjutan: Tanpa residu kimia, aman untuk tanaman, lingkungan, dan kesehatan",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml PHC Fungisida per liter air",
        "Semprotkan ke seluruh bagian tanaman, terutama bagian yang terinfeksi jamur",
        "Aplikasikan setiap 7-10 hari sebagai pencegahan atau pengobatan",
      ],
      image: "/Katalog Dokter Tani/phc-fungisida/_DSF1534.JPG",
    },
    cta: "Jangan biarkan jamur merusak panen Anda. Beli PHC Fungisida Dokter Tani Hari Ini & Nikmati Panen Sehat Bebas Penyakit!",
    reviews: [
      { id: "r33", name: "Pak Hartono", rating: 5, date: "2025-12-13", comment: "Blas pada padi saya terkendali dengan cepat. PHC Fungisida memang andalan!" },
      { id: "r34", name: "Ibu Lastri", rating: 5, date: "2025-11-25", comment: "Patek pada cabai hilang setelah 3x penyemprotan. Panen aman!" },
    ],
    relatedProductIds: ["2", "13", "10"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "16",
    slug: "phc-jagung",
    name: "PHC Jagung Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["PHC Jagung", "Anti Bulai", "Tongkol Penuh", "Batang Kokoh"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/phc-jagung/500/phc-jagung-1L_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-jagung/500/phc-jagung-1L_01.jpg",
      "/Katalog Dokter Tani/phc-jagung/500/phc-jagung-1L_02.jpg",
      "/Katalog Dokter Tani/phc-jagung/500/phc-jagung-1L_03.jpg",
      "/Katalog Dokter Tani/phc-jagung/250/phc-jagung-1L_04.jpg",
      "/Katalog Dokter Tani/phc-jagung/250/phc-jagung-1L_05.jpg",
    ],
    metaTitle: "PHC Jagung Dokter Tani - Pupuk & Pelindung Jagung Anti Bulai & Tongkol Penuh",
    metaDescription: "Maksimalkan panen jagung Anda dengan PHC Jagung Dokter Tani! Paket nutrisi & perlindungan khusus jagung, cegah bulai, batang kokoh, & hasilkan tongkol penuh.",
    focusKeyword: "PHC Jagung Dokter Tani",
    hook: "Penyakit bulai adalah momok utama bagi petani jagung, bisa menyebabkan gagal panen total. Belum lagi masalah batang rebah atau tongkol yang tidak terisi penuh.",
    description: "PHC Jagung Dokter Tani adalah solusi terintegrasi yang dirancang khusus untuk budidaya jagung yang sukses. Kombinasi nutrisi esensial dan perlindungan hayati yang disesuaikan dengan kebutuhan spesifik tanaman jagung.",
    benefits: [
      "Cegah Penyakit Bulai: Melindungi jagung muda dari serangan bulai yang mematikan",
      "Batang Kokoh: Membangun batang jagung yang kuat, tahan rebah, dan mampu menopang tongkol besar",
      "Tongkol Penuh Bernas: Memastikan pengisian bulir jagung yang penuh hingga ujung, meningkatkan bobot pipilan",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml PHC Jagung per liter air",
        "Semprotkan ke seluruh bagian tanaman jagung sejak fase vegetatif",
        "Ulangi setiap 10-14 hari hingga fase pengisian biji",
      ],
      image: "/Katalog Dokter Tani/phc-jagung/500/phc-jagung-1L_03.jpg",
    },
    cta: "Raih panen jagung melimpah dan berkualitas tinggi. Dapatkan PHC Jagung Dokter Tani Sekarang & Amankan Hasil Panen Anda!",
    reviews: [
      { id: "r35", name: "Pak Suroto", rating: 5, date: "2025-12-08", comment: "Jagung bebas bulai dan tongkol penuh sampai ujung! Hasil memuaskan." },
      { id: "r36", name: "Mas Fajar", rating: 5, date: "2025-11-22", comment: "PHC Jagung bikin batang kokoh dan pipilan berat. Top!" },
    ],
    relatedProductIds: ["24", "3", "14"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "17",
    slug: "phc-kobis",
    name: "PHC Kobis Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["PHC Kobis", "Anti Akar Gada", "Busuk Lunak", "Kubis Sehat"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/phc-kobis/500/phc-kobis-1L_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-kobis/500/phc-kobis-1L_01.jpg",
      "/Katalog Dokter Tani/phc-kobis/500/phc-kobis-1L_02.jpg",
      "/Katalog Dokter Tani/phc-kobis/500/phc-kobis-1L_03.jpg",
      "/Katalog Dokter Tani/phc-kobis/250/phc-kobis-1L_04.jpg",
      "/Katalog Dokter Tani/phc-kobis/250/phc-kobis-1L_05.jpg",
    ],
    metaTitle: "PHC Kobis Dokter Tani - Pelindung Kubis Anti Akar Gada & Busuk Lunak Organik",
    metaDescription: "Lindungi tanaman kubis Anda dari akar gada & busuk lunak dengan PHC Kobis Dokter Tani! Solusi organik ini jaga kesehatan kubis, daun lebar, & hasilkan panen optimal.",
    focusKeyword: "PHC Kobis Dokter Tani",
    hook: "Penyakit akar gada dan busuk lunak adalah masalah umum yang sering menyerang tanaman kubis-kubisan, menyebabkan kerugian besar. Tanaman layu, kerdil, dan akhirnya mati.",
    description: "PHC Kobis Dokter Tani adalah formula perlindungan khusus untuk tanaman kubis. Mengandung mikroba baik yang spesifik untuk mengatasi akar gada dan busuk lunak, menghasilkan kubis sehat dan daun lebar.",
    benefits: [
      "Atasi Akar Gada: Menekan patogen penyebab akar gada, memungkinkan akar tumbuh normal dan menyerap nutrisi",
      "Cegah Busuk Lunak: Melindungi tanaman dari bakteri penyebab busuk lunak yang merusak daun dan batang",
      "Kubis Sehat & Daun Lebar: Tanaman kubis akan tumbuh sehat, daun lebar, dan menghasilkan panen berkualitas tinggi",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml PHC Kobis per liter air",
        "Siramkan ke area perakaran atau semprotkan ke seluruh bagian tanaman kubis",
        "Aplikasikan sejak awal tanam, ulangi setiap 7-14 hari",
      ],
      image: "/Katalog Dokter Tani/phc-kobis/500/phc-kobis-1L_03.jpg",
    },
    cta: "Jaga kubis Anda tetap sehat dan subur. Pesan PHC Kobis Dokter Tani Hari Ini & Nikmati Panen Kubis Terbaik!",
    reviews: [
      { id: "r37", name: "Pak Tarno", rating: 5, date: "2025-12-02", comment: "Kubis saya bebas akar gada! Daunnya lebar-lebar dan krop besar." },
      { id: "r38", name: "Ibu Sri", rating: 4, date: "2025-11-15", comment: "Efektif untuk cegah busuk lunak. Kubis sehat sampai panen." },
    ],
    relatedProductIds: ["15", "30", "20"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "18",
    slug: "phc-padi",
    name: "PHC Padi Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["PHC Padi", "Anti Blas", "Anti Kresek", "Anakan Produktif"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/phc-padi/images/phc-padi_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-padi/images/phc-padi_01.jpg",
      "/Katalog Dokter Tani/phc-padi/images/phc-padi_02.jpg",
      "/Katalog Dokter Tani/phc-padi/images/phc-padi_03.jpg",
      "/Katalog Dokter Tani/phc-padi/images/phc-padi_04.jpg",
      "/Katalog Dokter Tani/phc-padi/images/phc-padi_05.jpg",
    ],
    metaTitle: "PHC Padi Dokter Tani - Pupuk & Pelindung Padi Anti Blas, Kresek & Anakan Produktif",
    metaDescription: "Tingkatkan hasil panen padi dengan PHC Padi Dokter Tani! Solusi lengkap cegah blas & kresek, rangsang anakan produktif, untuk padi sehat, batang kuat, & bulir bernas.",
    focusKeyword: "PHC Padi Dokter Tani",
    hook: "Penyakit blas dan kresek adalah dua ancaman utama yang bisa merusak sawah Anda, menyebabkan kerugian besar. Belum lagi masalah anakan padi yang sedikit atau bulir yang tidak bernas.",
    description: "PHC Padi Dokter Tani adalah solusi komprehensif untuk budidaya padi yang optimal. Menggabungkan nutrisi esensial dan perlindungan hayati untuk padi sehat dan produktif. Rating 4.9/5.0 di Shopee!",
    benefits: [
      "Atasi Blas & Kresek: Melindungi tanaman dari serangan jamur blas dan bakteri kresek yang mematikan",
      "Anakan Produktif: Merangsang pembentukan anakan padi yang lebih banyak dan produktif",
      "Bulir Bernas Sempurna: Membantu pengisian bulir agar bernas hingga 80-90%, meningkatkan bobot gabah",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml PHC Padi per liter air",
        "Semprotkan ke seluruh bagian tanaman padi dari fase anakan aktif",
        "Ulangi setiap 10-14 hari hingga menjelang panen",
      ],
      image: "/Katalog Dokter Tani/phc-padi/images/phc-padi_03.jpg",
    },
    cta: "Raih panen padi melimpah dan bebas penyakit. Dapatkan PHC Padi Dokter Tani Sekarang & Amankan Hasil Panen Anda!",
    reviews: [
      { id: "r39", name: "Pak Wagiman", rating: 5, date: "2025-12-11", comment: "Anakan produktif meningkat drastis! Bulir bernas semua. PHC Padi memang juara!" },
      { id: "r40", name: "Ibu Sumarni", rating: 5, date: "2025-11-27", comment: "Padi saya bebas blas dan kresek. Panen meningkat 25% dibanding musim lalu." },
    ],
    relatedProductIds: ["4", "11", "28"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "19",
    slug: "phc-sawit",
    name: "PHC Sawit Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["PHC Sawit", "Anti Ganoderma", "Kelapa Sawit", "TBS Melimpah"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_01.jpg",
      "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_02.jpg",
      "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_03.jpg",
      "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_04.jpg",
      "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_05.jpg",
    ],
    metaTitle: "PHC Sawit Dokter Tani - Pelindung Kelapa Sawit Anti Ganoderma & Penyerapan Pupuk Optimal",
    metaDescription: "Lindungi kelapa sawit Anda dari Ganoderma (busuk pangkal batang) & optimalkan penyerapan pupuk dengan PHC Sawit Dokter Tani! Solusi organik untuk sawit sehat & produktif.",
    focusKeyword: "PHC Sawit Dokter Tani",
    hook: "Penyakit Ganoderma (busuk pangkal batang) adalah momok terbesar bagi perkebunan kelapa sawit, bisa mematikan pohon dan menyebabkan kerugian miliaran rupiah.",
    description: "PHC Sawit Dokter Tani diformulasikan khusus untuk menjaga kesehatan dan produktivitas perkebunan kelapa sawit. Mikroba baik bekerja sinergis menekan patogen Ganoderma dan mengoptimalkan penyerapan pupuk.",
    benefits: [
      "Atasi Ganoderma: Mikroba baik menekan patogen Ganoderma, mencegah dan mengobati busuk pangkal batang",
      "Optimalkan Penyerapan Pupuk: Memperbaiki kondisi tanah di sekitar perakaran untuk memanfaatkan nutrisi secara maksimal",
      "TBS Melimpah: Pohon sawit lebih sehat, tahan penyakit, dan menghasilkan tandan buah segar yang berkualitas",
    ],
    usage: {
      steps: [
        "Campurkan 10-20 ml PHC Sawit per liter air",
        "Siramkan ke area perakaran dan pangkal batang kelapa sawit",
        "Aplikasikan setiap 30 hari untuk perlindungan berkelanjutan",
      ],
      image: "/Katalog Dokter Tani/phc-sawit/images/phc-sawit_03.jpg",
    },
    cta: "Amankan investasi sawit Anda dari Ganoderma. Beli PHC Sawit Dokter Tani Hari Ini & Raih Panen TBS Maksimal!",
    reviews: [
      { id: "r41", name: "Pak Syamsul", rating: 5, date: "2025-12-05", comment: "Ganoderma di kebun saya terkendali. TBS meningkat setelah rutin pakai PHC Sawit." },
      { id: "r42", name: "Mas Roni", rating: 5, date: "2025-11-20", comment: "Investasi jangka panjang terbaik untuk perkebunan sawit." },
    ],
    relatedProductIds: ["3", "14", "20"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "20",
    slug: "phc-semua-tanaman",
    name: "PHC Semua Tanaman Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["PHC Universal", "Pupuk Organik", "Serbaguna", "Multifungsi"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/phc-semua-tanaman/500/phc-semua-tanaman-1L_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-semua-tanaman/500/phc-semua-tanaman-1L_01.jpg",
      "/Katalog Dokter Tani/phc-semua-tanaman/500/phc-semua-tanaman-1L_02.jpg",
      "/Katalog Dokter Tani/phc-semua-tanaman/500/phc-semua-tanaman-1L_03.jpg",
      "/Katalog Dokter Tani/phc-semua-tanaman/250/phc-semua-tanaman-1L_04.jpg",
      "/Katalog Dokter Tani/phc-semua-tanaman/250/phc-semua-tanaman-1L_05.jpg",
    ],
    metaTitle: "PHC Semua Tanaman Dokter Tani - Pupuk & Pelindung Organik Universal Multifungsi",
    metaDescription: "Jaga kesehatan semua jenis tanaman Anda dengan PHC Semua Tanaman Dokter Tani! Solusi organik multifungsi untuk perlindungan penyakit, pembenah tanah, & nutrisi lengkap.",
    focusKeyword: "PHC Semua Tanaman Dokter Tani",
    hook: "Anda memiliki berbagai jenis tanaman dan bingung memilih pupuk serta pelindung yang tepat? Atau ingin solusi praktis yang aman untuk semua tanaman Anda?",
    description: "PHC Semua Tanaman Dokter Tani adalah jawaban universal. Produk organik multifungsi ini mengandung konsorsium mikroba baik yang bekerja sinergis sebagai pelindung, pembenah tanah, dan penyedia nutrisi. Praktis, efektif, dan aman!",
    benefits: [
      "Pelindung Universal: Melindungi berbagai jenis tanaman dari serangan patogen umum (jamur & bakteri)",
      "Pembenah Tanah: Memperbaiki struktur tanah, meningkatkan kesuburan, dan mengoptimalkan penyerapan nutrisi",
      "Nutrisi Lengkap: Menyediakan unsur hara esensial untuk pertumbuhan vegetatif dan generatif yang seimbang",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml PHC Semua Tanaman per liter air",
        "Semprotkan atau siramkan ke seluruh jenis tanaman di kebun Anda",
        "Aplikasikan setiap 7-14 hari untuk hasil optimal",
      ],
      image: "/Katalog Dokter Tani/phc-semua-tanaman/500/phc-semua-tanaman-1L_03.jpg",
    },
    cta: "Berikan perlindungan terbaik dan nutrisi lengkap untuk semua tanaman Anda. Dapatkan PHC Semua Tanaman Sekarang & Nikmati Kebun Sehat Sepanjang Tahun!",
    reviews: [
      { id: "r43", name: "Ibu Ratna", rating: 5, date: "2025-12-09", comment: "Praktis banget! Satu produk untuk semua tanaman di kebun saya. Hasilnya memuaskan." },
      { id: "r44", name: "Mas Wahyu", rating: 5, date: "2025-11-24", comment: "Tanaman hias, sayuran, dan buah-buahan semuanya sehat dan subur." },
    ],
    relatedProductIds: ["13", "15", "14"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "21",
    slug: "phc-tikus",
    name: "PHC Tikus Dokter Tani",
    category: "PHC (Pupuk Hayati Cair)",
    tags: ["Pengusir Tikus", "Repellent", "Organik", "Anti Burung"],
    stock: "Tersedia",
    unit: "500 ml",
    image: "/Katalog Dokter Tani/phc-tikus/images/phc-tikus_01.jpg",
    images: [
      "/Katalog Dokter Tani/phc-tikus/images/phc-tikus_01.jpg",
      "/Katalog Dokter Tani/phc-tikus/preview-mobile.png",
      "/Katalog Dokter Tani/phc-tikus/preview-website.png",
    ],
    metaTitle: "PHC Tikus Dokter Tani - Pengusir Tikus & Burung Organik Aroma Ajaib Aman Lingkungan",
    metaDescription: "Bebaskan lahan Anda dari serangan tikus & burung dengan PHC Tikus Dokter Tani! Repellent hayati aroma ajaib ini efektif usir hama tanpa racun, aman bagi lingkungan.",
    focusKeyword: "PHC Tikus Dokter Tani",
    hook: "Tikus dan burung adalah hama yang sangat merugikan, terutama di fase persemaian dan menjelang panen. Penggunaan racun tikus kimia berbahaya bagi lingkungan dan hewan lain.",
    description: "PHC Tikus Dokter Tani adalah solusi inovatif dan ramah lingkungan. Bekerja sebagai repellent hayati dengan \"aroma ajaib\" yang tidak disukai hama, namun aman bagi tanaman, manusia, dan hewan peliharaan.",
    benefits: [
      "Usir Hama Tanpa Racun: Aroma spesifik mengganggu indra penciuman tikus dan burung, membuat mereka menjauh",
      "Aman & Efektif: Tidak membunuh hama, hanya mengusir, menjaga keseimbangan ekosistem",
      "Perlindungan Optimal: Melindungi persemaian, batang muda, dan buah dari kerusakan akibat serangan hama",
    ],
    usage: {
      steps: [
        "Semprotkan PHC Tikus di area sekitar tanaman, pematang sawah, atau tempat jalur tikus",
        "Ulangi penyemprotan setiap 7-14 hari atau setelah hujan deras",
        "Untuk burung, semprotkan pada area persemaian dan tanaman muda yang rentan",
      ],
      image: "/Katalog Dokter Tani/phc-tikus/preview-website.png",
    },
    cta: "Lindungi panen Anda dari tikus dan burung tanpa merusak lingkungan. Beli PHC Tikus Dokter Tani Hari Ini & Panen Lebih Tenang!",
    reviews: [
      { id: "r45", name: "Pak Sugeng", rating: 5, date: "2025-12-07", comment: "Tikus di sawah saya berkurang drastis! Aroma PHC Tikus memang ajaib." },
      { id: "r46", name: "Mas Yanto", rating: 4, date: "2025-11-19", comment: "Efektif juga untuk usir burung di persemaian. Aman dan tidak bau menyengat." },
    ],
    relatedProductIds: ["18", "11", "20"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "22",
    slug: "poc-akar",
    name: "POC Akar Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Akar", "Perangsang Akar", "Root Booster", "Pindah Tanam"],
    stock: "Tersedia",
    unit: "500 ml",
    image: "/Katalog Dokter Tani/poc-akar/images/poc-akar_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-akar/images/poc-akar_01.jpg",
      "/Katalog Dokter Tani/poc-akar/images/poc-akar_02.jpg",
      "/Katalog Dokter Tani/poc-akar/images/poc-akar_03.jpg",
      "/Katalog Dokter Tani/poc-akar/images/poc-akar_04.jpg",
      "/Katalog Dokter Tani/poc-akar/images/poc-akar_05.jpg",
    ],
    metaTitle: "POC Akar Dokter Tani - Pupuk Organik Perangsang Akar Kuat, Cepat Tumbuh & Anti Stres Pindah Tanam",
    metaDescription: "Percepat pertumbuhan akar & adaptasi tanaman dengan POC Akar Dokter Tani! Pupuk organik cair ini jamin akar kuat, sehat, & tidak stres saat pindah tanam.",
    focusKeyword: "POC Akar Dokter Tani",
    hook: "Fase persemaian dan pindah tanam adalah masa kritis bagi tanaman. Bibit seringkali stres, layu, atau bahkan mati karena akarnya belum kuat beradaptasi.",
    description: "POC Akar Dokter Tani adalah \"vitamin\" terbaik untuk sistem perakaran tanaman. Dirancang khusus sebagai perangsang akar (root booster) yang ampuh. Produk wajib bagi pembibitan dan petani yang sering melakukan pindah tanam.",
    benefits: [
      "Akar Kuat & Lebat: Merangsang pembentukan akar serabut yang banyak, memperluas jangkauan penyerapan nutrisi",
      "Anti Stres Pindah Tanam: Membantu tanaman beradaptasi dengan cepat di lingkungan baru, mengurangi risiko kematian bibit",
      "Pondasi Pertumbuhan Optimal: Dengan sistem perakaran yang sehat, tanaman akan tumbuh vegetatif lebih subur dan kokoh",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Akar per liter air",
        "Rendam bibit selama 15-30 menit sebelum tanam, atau siramkan ke area perakaran setelah tanam",
        "Ulangi penyiraman setiap 7-14 hari pada fase awal pertumbuhan",
      ],
      image: "/Katalog Dokter Tani/poc-akar/images/poc-akar_03.jpg",
    },
    cta: "Bangun pondasi tanaman yang kuat sejak awal. Dapatkan POC Akar Dokter Tani Sekarang & Pastikan Bibit Anda Tumbuh Sempurna!",
    reviews: [
      { id: "r47", name: "Pak Jumadi", rating: 5, date: "2025-12-12", comment: "Bibit cabai saya tidak ada yang mati setelah pindah tanam. POC Akar sangat membantu!" },
      { id: "r48", name: "Ibu Nining", rating: 5, date: "2025-11-28", comment: "Akar tanaman jadi lebat dan kuat. Tanaman tumbuh lebih cepat dari biasanya." },
    ],
    relatedProductIds: ["1", "23", "30"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "23",
    slug: "poc-cabai",
    name: "POC Cabai Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Cabai", "Pelebat Buah", "Anti Rontok", "Cabai Pedas"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_01.jpg",
      "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_02.jpg",
      "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_03.jpg",
      "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_04.jpg",
      "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_05.jpg",
    ],
    metaTitle: "POC Cabai Dokter Tani - Pupuk Organik Pelebat Buah Cabai, Anti Rontok & Patek",
    metaDescription: "Ingin panen cabai lebat, pedas, dan bebas patek? POC Cabai Dokter Tani solusinya! Pupuk organik cair ini optimalkan pembungaan, pembuahan, cegah rontok.",
    focusKeyword: "POC Cabai Dokter Tani",
    hook: "Budidaya cabai seringkali dihadapkan pada masalah bunga dan buah rontok, buah kecil, atau serangan patek yang merusak. Ini bisa membuat petani frustrasi dan merugi.",
    description: "POC Cabai Dokter Tani adalah nutrisi spesifik untuk memaksimalkan produksi tanaman cabai. Kaya akan unsur hara makro dan mikro, serta hormon pertumbuhan esensial untuk fase generatif cabai. Rahasia petani cabai sukses!",
    benefits: [
      "Bunga & Buah Lebat: Mengoptimalkan pembentukan bunga, mencegah kerontokan, dan memperbanyak buah cabai",
      "Kualitas Buah Unggul: Meningkatkan bobot, ukuran, dan tingkat kepedasan buah cabai",
      "Ketahanan Penyakit: Memperkuat daya tahan tanaman terhadap serangan patek dan penyakit lainnya",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Cabai per liter air",
        "Semprotkan ke seluruh bagian tanaman cabai, terutama saat fase pembungaan",
        "Aplikasikan setiap 7-10 hari untuk hasil panen melimpah",
      ],
      image: "/Katalog Dokter Tani/poc-cabai/500/poc-cabai_03.jpg",
    },
    cta: "Wujudkan panen cabai melimpah dan berkualitas. Beli POC Cabai Dokter Tani Hari Ini & Raih Keuntungan Maksimal!",
    reviews: [
      { id: "r49", name: "Pak Rustam", rating: 5, date: "2025-12-14", comment: "Cabai saya berbuah lebat tanpa rontok! POC Cabai memang top." },
      { id: "r50", name: "Ibu Mimin", rating: 5, date: "2025-11-30", comment: "Buah cabai besar-besar dan pedas. Yang paling penting, bebas patek!" },
    ],
    relatedProductIds: ["10", "1", "15"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "24",
    slug: "poc-jagung",
    name: "POC Jagung Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Jagung", "Pengisi Bulir", "Batang Kokoh", "Anti Rebah"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_01.jpg",
      "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_02.jpg",
      "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_03.jpg",
      "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_04.jpg",
      "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_05.jpg",
    ],
    metaTitle: "POC Jagung Dokter Tani - Pupuk Organik Pengisi Bulir Jagung Penuh & Batang Kokoh Anti Rebah",
    metaDescription: "Dapatkan panen jagung maksimal dengan POC Jagung Dokter Tani! Pupuk organik cair ini fokus pada batang kokoh, anti rebah, & pengisian bulir penuh hingga ujung.",
    focusKeyword: "POC Jagung Dokter Tani",
    hook: "Masalah batang jagung yang mudah rebah saat berbuah lebat atau tongkol yang tidak terisi penuh seringkali mengurangi hasil panen Anda.",
    description: "POC Jagung Dokter Tani adalah formula nutrisi khusus untuk mengoptimalkan pertumbuhan dan hasil panen jagung. Difokuskan untuk batang kokoh, bulir penuh bernas, dan pertumbuhan seragam.",
    benefits: [
      "Batang Kokoh Anti Rebah: Membangun batang jagung kuat, mampu menopang tongkol besar dan berat",
      "Bulir Penuh Bernas: Memastikan pengisian bulir jagung penuh hingga ujung, meningkatkan bobot pipilan",
      "Pertumbuhan Seragam: Tanaman jagung tumbuh lebih seragam dan sehat",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Jagung per liter air",
        "Semprotkan ke seluruh bagian tanaman jagung sejak fase vegetatif",
        "Ulangi setiap 10-14 hari hingga fase pengisian biji",
      ],
      image: "/Katalog Dokter Tani/poc-jagung/images/poc-jagung_03.jpg",
    },
    cta: "Raih panen jagung terbaik Anda. Pesan POC Jagung Dokter Tani Sekarang & Tingkatkan Bobot Pipilan Anda!",
    reviews: [
      { id: "r51", name: "Pak Hasan", rating: 5, date: "2025-12-10", comment: "Tongkol jagung penuh sampai ujung! Pipilan berat dan kering sempurna." },
      { id: "r52", name: "Mas Andri", rating: 5, date: "2025-11-26", comment: "Batang jagung kokoh dan tidak rebah walau angin kencang. Top!" },
    ],
    relatedProductIds: ["16", "3", "14"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "25",
    slug: "poc-kakao",
    name: "POC Kakao Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Kakao", "Buah Kakao", "Anti Busuk", "Rendemen Tinggi"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_01.jpg",
      "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_02.jpg",
      "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_03.jpg",
      "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_04.jpg",
      "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_05.jpg",
    ],
    metaTitle: "POC Kakao Dokter Tani - Pupuk Organik Pembentuk Buah Kakao Berkualitas & Anti Busuk",
    metaDescription: "Tingkatkan kualitas & rendemen kakao dengan POC Kakao Dokter Tani! Pupuk organik cair ini optimalkan pembentukan buah, cegah busuk, & hasilkan biji kakao bernas.",
    focusKeyword: "POC Kakao Dokter Tani",
    hook: "Buah kakao sering busuk sebelum matang atau bijinya kecil dan kurang bernas? Ini mengurangi kualitas dan harga jual kakao Anda.",
    description: "POC Kakao Dokter Tani adalah nutrisi esensial untuk perkebunan kakao produktif. Dirancang khusus untuk mengoptimalkan pembentukan buah kakao, cegah busuk, dan hasilkan biji bernas berkualitas ekspor.",
    benefits: [
      "Cegah Busuk Buah: Melindungi buah kakao dari serangan jamur dan bakteri penyebab busuk",
      "Biji Bernas & Berkualitas: Meningkatkan rendemen biji kakao, biji lebih bernas dengan aroma dan rasa khas",
      "Pohon Produktif: Menjaga kesehatan pohon kakao agar tetap produktif menghasilkan buah secara konsisten",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Kakao per liter air",
        "Semprotkan ke seluruh bagian tanaman kakao atau siramkan ke area perakaran",
        "Aplikasikan setiap 14-21 hari untuk hasil optimal",
      ],
      image: "/Katalog Dokter Tani/poc-kakao/1000/poc-kakao_03.jpg",
    },
    cta: "Wujudkan panen kakao berkualitas tinggi. Dapatkan POC Kakao Dokter Tani Hari Ini & Tingkatkan Nilai Jual Kakao Anda!",
    reviews: [
      { id: "r53", name: "Pak Daeng", rating: 5, date: "2025-12-06", comment: "Rendemen biji kakao meningkat signifikan. Kualitas jauh lebih baik!" },
      { id: "r54", name: "Mas Akbar", rating: 5, date: "2025-11-22", comment: "Buah kakao tidak busuk lagi. Biji bernas dan aroma khas." },
    ],
    relatedProductIds: ["27", "31", "14"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "26",
    slug: "poc-kedelai",
    name: "POC Kedelai Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Kedelai", "Peningkat Polong", "Biji Bernas", "Fiksasi Nitrogen"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_01.jpg",
      "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_02.jpg",
      "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_03.jpg",
      "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_04.jpg",
      "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_05.jpg",
    ],
    metaTitle: "POC Kedelai Dokter Tani - Pupuk Organik Peningkat Polong Kedelai & Biji Bernas",
    metaDescription: "Maksimalkan hasil panen kedelai Anda dengan POC Kedelai Dokter Tani! Pupuk organik cair ini bantu fiksasi nitrogen, perbanyak polong, & hasilkan biji bernas.",
    focusKeyword: "POC Kedelai Dokter Tani",
    hook: "Tanaman kedelai kurang subur, polongnya sedikit, atau bijinya kecil dan tidak bernas? Ini bisa disebabkan oleh kurangnya ketersediaan nitrogen.",
    description: "POC Kedelai Dokter Tani dirancang untuk mengoptimalkan produktivitas tanaman kedelai. Tidak hanya menyediakan unsur hara, tetapi juga membantu fiksasi nitrogen optimal dan peningkatan protein biji kedelai.",
    benefits: [
      "Fiksasi Nitrogen Optimal: Membantu aktivitas mikroba dalam bintil akar untuk mengikat nitrogen dari udara",
      "Polong Lebat & Biji Bernas: Merangsang pembentukan polong lebih banyak dan pengisian biji bernas sempurna",
      "Tingkatkan Protein: Dengan nutrisi seimbang, kandungan protein pada biji kedelai juga meningkat",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Kedelai per liter air",
        "Semprotkan ke seluruh bagian tanaman kedelai dari fase vegetatif",
        "Ulangi setiap 10-14 hari hingga fase pengisian polong",
      ],
      image: "/Katalog Dokter Tani/poc-kedelai/500/poc-kedelai_03.jpg",
    },
    cta: "Tingkatkan panen kedelai Anda secara signifikan. Pesan POC Kedelai Dokter Tani Sekarang & Raih Keuntungan Lebih!",
    reviews: [
      { id: "r55", name: "Pak Sumardi", rating: 5, date: "2025-12-03", comment: "Polong kedelai meningkat 40%! Biji besar-besar dan bernas." },
      { id: "r56", name: "Ibu Tini", rating: 5, date: "2025-11-19", comment: "Hasil panen kedelai terbaik setelah pakai POC ini." },
    ],
    relatedProductIds: ["22", "14", "3"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "27",
    slug: "poc-kopi",
    name: "POC Kopi Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Kopi", "Aroma Kopi", "Biji Kopi Premium", "Kualitas Ekspor"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_01.jpg",
      "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_02.jpg",
      "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_03.jpg",
      "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_04.jpg",
      "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_05.jpg",
    ],
    metaTitle: "POC Kopi Dokter Tani - Pupuk Organik Peningkat Aroma & Rasa Kopi Premium",
    metaDescription: "Hasilkan biji kopi premium dengan POC Kopi Dokter Tani! Pupuk organik cair ini tingkatkan aroma & rasa, cegah rontok, & percepat pematangan buah kopi secara seragam.",
    focusKeyword: "POC Kopi Dokter Tani",
    hook: "Kualitas biji kopi sangat menentukan harga jual. Jika buah kopi sering rontok, pematangan tidak seragam, atau aroma kurang kuat, maka nilai jual kopi Anda rendah.",
    description: "POC Kopi Dokter Tani adalah rahasia di balik biji kopi berkualitas premium. Diformulasikan khusus untuk memenuhi kebutuhan nutrisi tanaman kopi, dengan fokus pada peningkatan aroma, rasa, dan kualitas ekspor.",
    benefits: [
      "Aroma & Rasa Khas: Meningkatkan profil aroma dan rasa biji kopi, menjadikannya lebih kaya dan unik",
      "Anti Rontok & Pematangan Seragam: Mencegah kerontokan buah dini dan mempercepat pematangan seragam",
      "Kualitas Ekspor: Dengan nutrisi optimal, biji kopi memenuhi standar kualitas ekspor",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Kopi per liter air",
        "Semprotkan ke seluruh bagian tanaman kopi, terutama saat fase pembuahan dan pematangan",
        "Aplikasikan setiap 14-21 hari untuk hasil optimal",
      ],
      image: "/Katalog Dokter Tani/poc-kopi/images/poc-kopi_03.jpg",
    },
    cta: "Ciptakan kopi berkualitas dunia. Dapatkan POC Kopi Dokter Tani Hari Ini & Tingkatkan Nilai Jual Kopi Anda!",
    reviews: [
      { id: "r57", name: "Pak Samsul", rating: 5, date: "2025-12-08", comment: "Aroma kopi dari kebun saya makin harum setelah pakai POC Kopi. Pembeli puas!" },
      { id: "r58", name: "Mas Gilang", rating: 5, date: "2025-11-24", comment: "Pematangan buah seragam, mudah panen. Kualitas biji premium." },
    ],
    relatedProductIds: ["25", "31", "14"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "28",
    slug: "poc-padi",
    name: "POC Padi Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Padi", "Anakan Produktif", "Bulir Bernas", "Panen Melimpah"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/poc-padi/images/poc-padi_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-padi/images/poc-padi_01.jpg",
      "/Katalog Dokter Tani/poc-padi/images/poc-padi_02.jpg",
      "/Katalog Dokter Tani/poc-padi/images/poc-padi_03.jpg",
      "/Katalog Dokter Tani/poc-padi/images/poc-padi_04.jpg",
      "/Katalog Dokter Tani/poc-padi/images/poc-padi_05.jpg",
    ],
    metaTitle: "POC Padi Dokter Tani - Pupuk Organik Peningkat Anakan Padi & Bulir Bernas 90%",
    metaDescription: "Raih panen padi melimpah dengan POC Padi Dokter Tani! Pupuk organik cair ini tingkatkan anakan produktif, jamin bulir bernas 80-90%, & buat padi lebih sehat.",
    focusKeyword: "POC Padi Dokter Tani",
    hook: "Anakan padi yang sedikit, bulir yang kopong, atau padi yang mudah terserang penyakit adalah masalah umum yang menghambat petani mencapai panen maksimal.",
    description: "POC Padi Dokter Tani adalah kunci untuk produktivitas sawah yang maksimal. Dirancang khusus untuk mengoptimalkan pertumbuhan padi dari fase vegetatif hingga generatif. Rating 4.8/5.0 di Shopee dengan ratusan ulasan positif!",
    benefits: [
      "Anakan Produktif Melimpah: Merangsang pembentukan anakan produktif lebih banyak, setiap rumpun menghasilkan bulir melimpah",
      "Bulir Bernas Sempurna: Menjamin pengisian bulir padi hingga 80-90% bernas, meningkatkan bobot gabah",
      "Padi Sehat & Tahan Penyakit: Dengan nutrisi seimbang, tanaman padi lebih kuat tahan penyakit",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Padi per liter air",
        "Semprotkan ke seluruh bagian tanaman padi dari fase anakan aktif",
        "Ulangi setiap 10-14 hari hingga menjelang panen",
      ],
      image: "/Katalog Dokter Tani/poc-padi/images/poc-padi_03.jpg",
    },
    cta: "Maksimalkan hasil panen padi Anda. Beli POC Padi Dokter Tani Sekarang & Nikmati Panen Melimpah!",
    reviews: [
      { id: "r59", name: "Pak Sabar", rating: 5, date: "2025-12-11", comment: "Anakan padi meningkat dari 12 jadi 18 per rumpun! Bulir bernas semua." },
      { id: "r60", name: "Ibu Jumiyah", rating: 5, date: "2025-11-27", comment: "Hasil panen naik 30%. POC Padi Dokter Tani memang luar biasa!" },
    ],
    relatedProductIds: ["4", "11", "18"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "29",
    slug: "poc-salak",
    name: "POC Salak Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Salak", "Pemanis Buah", "Daging Tebal", "Pohon Produktif"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/poc-salak/images/poc-salak_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-salak/images/poc-salak_01.jpg",
      "/Katalog Dokter Tani/poc-salak/images/poc-salak_02.jpg",
      "/Katalog Dokter Tani/poc-salak/images/poc-salak_03.jpg",
      "/Katalog Dokter Tani/poc-salak/images/poc-salak_04.jpg",
      "/Katalog Dokter Tani/poc-salak/images/poc-salak_05.jpg",
    ],
    metaTitle: "POC Salak Dokter Tani - Pupuk Organik Pemanis Buah Salak, Daging Tebal & Pohon Produktif",
    metaDescription: "Panen salak manis, daging tebal, & pohon tetap produktif dengan POC Salak Dokter Tani! Pupuk organik cair ini optimalkan kualitas buah & jaga kesehatan pohon salak.",
    focusKeyword: "POC Salak Dokter Tani",
    hook: "Buah salak kurang manis, dagingnya tipis, atau pohon salak sudah tua dan jarang berbuah? Ini mengurangi nilai jual dan produktivitas kebun salak Anda.",
    description: "POC Salak Dokter Tani adalah nutrisi premium yang diformulasikan khusus untuk tanaman salak. Meningkatkan kadar gula, daging buah tebal, dan menjaga pohon tetap produktif berkelanjutan.",
    benefits: [
      "Salak Manis & Daging Tebal: Meningkatkan kadar gula, membuat buah salak lebih manis, berdaging tebal, dan berukuran seragam",
      "Pohon Produktif Berkelanjutan: Menjaga kesehatan dan vitalitas pohon salak, bahkan pada pohon yang sudah tua",
      "Kualitas Unggul: Dengan nutrisi tepat, buah salak memiliki kualitas premium yang dicari konsumen",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Salak per liter air",
        "Siramkan ke area perakaran pohon salak",
        "Aplikasikan setiap 14-21 hari untuk hasil optimal",
      ],
      image: "/Katalog Dokter Tani/poc-salak/images/poc-salak_03.jpg",
    },
    cta: "Wujudkan panen salak berkualitas tinggi. Pesan POC Salak Dokter Tani Hari Ini & Tingkatkan Keuntungan Kebun Salak Anda!",
    reviews: [
      { id: "r61", name: "Pak Sarimin", rating: 5, date: "2025-12-04", comment: "Salak pondoh saya jadi lebih manis dan besar! Pembeli makin banyak." },
      { id: "r62", name: "Ibu Karsi", rating: 5, date: "2025-11-20", comment: "Pohon tua yang sudah jarang berbuah, sekarang rajin berbuah lagi." },
    ],
    relatedProductIds: ["31", "22", "14"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "30",
    slug: "poc-sayuran-daun",
    name: "POC Sayuran Daun Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Sayuran", "Pelebat Daun", "Hijau Segar", "Anti Layu"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_01.jpg",
      "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_02.jpg",
      "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_03.jpg",
      "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_04.jpg",
      "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_05.jpg",
    ],
    metaTitle: "POC Sayuran Daun Dokter Tani - Pupuk Organik Pelebat Daun Hijau Segar & Anti Layu",
    metaDescription: "Dapatkan sayuran daun lebat, hijau segar, & tidak cepat layu dengan POC Sayuran Daun Dokter Tani! Pupuk organik cair ini optimalkan pertumbuhan vegetatif.",
    focusKeyword: "POC Sayuran Daun Dokter Tani",
    hook: "Sayuran daun sering kerdil, daunnya kuning, atau cepat layu setelah dipanen? Ini mengurangi kualitas dan daya jual sayuran Anda.",
    description: "POC Sayuran Daun Dokter Tani adalah rahasia di balik sayuran daun yang subur dan segar. Dirancang khusus untuk sawi, kangkung, selada, dan bayam. Pilihan favorit pekebun rumahan dan petani sayuran.",
    benefits: [
      "Daun Lebat & Hijau Segar: Mempercepat pertumbuhan, membuat daun lebih lebar, hijau segar, dan menarik",
      "Anti Cepat Layu: Meningkatkan ketahanan sel daun, sayuran tidak cepat layu setelah panen",
      "Sayuran Sehat & Berkualitas: Dengan nutrisi optimal, sayuran daun berkualitas tinggi siap dikonsumsi atau dijual",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Sayuran Daun per liter air",
        "Semprotkan ke seluruh bagian tanaman sayuran daun",
        "Aplikasikan setiap 7-10 hari untuk hasil terbaik",
      ],
      image: "/Katalog Dokter Tani/poc-sayuran daun/500/poc-sayuran-daun_03.jpg",
    },
    cta: "Panen sayuran daun segar setiap hari. Dapatkan POC Sayuran Daun Dokter Tani Sekarang & Nikmati Hasil Terbaik!",
    reviews: [
      { id: "r63", name: "Ibu Wulan", rating: 5, date: "2025-12-13", comment: "Sawi dan kangkung saya tumbuh subur dan hijau segar! Laris manis di pasar." },
      { id: "r64", name: "Mas Fikri", rating: 5, date: "2025-11-29", comment: "Sayuran tidak cepat layu setelah dipetik. Pembeli puas dan repeat order terus." },
    ],
    relatedProductIds: ["22", "32", "20"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "31",
    slug: "poc-tanaman-buah",
    name: "POC Tanaman Buah Dokter Tani",
    category: "POC (Pupuk Organik Cair)",
    tags: ["POC Tanaman Buah", "Pelebat Buah", "Rajin Berbuah", "Buah Manis"],
    stock: "Tersedia",
    unit: "500 ml / 1 L",
    image: "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_01.jpg",
    images: [
      "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_01.jpg",
      "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_02.jpg",
      "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_03.jpg",
      "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_04.jpg",
      "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_05.jpg",
    ],
    metaTitle: "POC Tanaman Buah Dokter Tani - Pupuk Organik Pelebat Buah Segala Jenis Tanaman",
    metaDescription: "Ingin semua tanaman buah Anda rajin berbuah, lebat, & berkualitas? POC Tanaman Buah Dokter Tani solusinya! Pupuk organik cair nutrisi lengkap untuk buah melimpah.",
    focusKeyword: "POC Tanaman Buah Dokter Tani",
    hook: "Pohon buah sudah lama tidak berbuah, atau buahnya sedikit dan rasanya kurang manis? Ini masalah umum yang sering membuat pemilik pohon buah kecewa.",
    description: "POC Tanaman Buah Dokter Tani adalah solusi universal untuk semua jenis pohon buah. Menyediakan nutrisi makro dan mikro lengkap, esensial untuk setiap fase pertumbuhan tanaman buah. Pilihan terbaik untuk kebun buah rumahan maupun komersial.",
    benefits: [
      "Rajin Berbuah & Lebat: Merangsang tanaman untuk rajin berbuah, memperbanyak jumlah buah per pohon",
      "Kualitas Buah Premium: Meningkatkan kualitas rasa, ukuran, dan warna buah, lebih manis dan menarik",
      "Pohon Sehat & Produktif: Menjaga kesehatan pohon buah agar selalu produktif dan menghasilkan buah konsisten",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml POC Tanaman Buah per liter air",
        "Semprotkan atau siramkan ke seluruh jenis tanaman buah",
        "Aplikasikan setiap 14-21 hari untuk hasil optimal",
      ],
      image: "/Katalog Dokter Tani/poc-tanaman buah/500/poc-tanaman-buah_03.jpg",
    },
    cta: "Jadikan semua pohon buah Anda produktif. Beli POC Tanaman Buah Dokter Tani Hari Ini & Nikmati Panen Buah Sepanjang Tahun!",
    reviews: [
      { id: "r65", name: "Pak Hariyanto", rating: 5, date: "2025-12-10", comment: "Semua pohon buah di halaman saya berbuah lebat! Jambu, mangga, rambutan semua sukses." },
      { id: "r66", name: "Ibu Lestari", rating: 5, date: "2025-11-25", comment: "Buah jeruk jadi lebih manis dan besar. POC ini memang andalan!" },
    ],
    relatedProductIds: ["7", "8", "9"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
  {
    id: "32",
    slug: "urea-organik",
    name: "Urea Dokter Tani (Organik Cair)",
    category: "Pupuk Organik",
    tags: ["Urea Organik", "Nitrogen Organik", "Hijau Daun", "Ramah Tanah"],
    stock: "Tersedia",
    unit: "1 L",
    image: "/Katalog Dokter Tani/urea/images/urea_01.jpg",
    images: [
      "/Katalog Dokter Tani/urea/images/urea_01.jpg",
      "/Katalog Dokter Tani/urea/images/urea_02.jpg",
      "/Katalog Dokter Tani/urea/images/urea_03.jpg",
      "/Katalog Dokter Tani/urea/images/urea_04.jpg",
      "/Katalog Dokter Tani/urea/images/urea_05.jpg",
    ],
    metaTitle: "Urea Dokter Tani - Pupuk Nitrogen Organik Cair Cepat Serap, Hijau Daun Instan & Ramah Tanah",
    metaDescription: "Dapatkan daun hijau instan tanpa merusak tanah dengan Urea Dokter Tani! Pupuk nitrogen organik cair ini cepat serap, ramah lingkungan, & cegah tanah masam.",
    focusKeyword: "Urea Dokter Tani",
    hook: "Ingin tanaman memiliki daun hijau segar dan pertumbuhan cepat, tapi khawatir penggunaan urea kimia akan merusak tanah dan membuatnya masam? Ada solusi yang lebih baik!",
    description: "Urea Dokter Tani adalah alternatif pupuk nitrogen yang inovatif dan ramah lingkungan. Berbeda dengan urea kimia konvensional, formulasi organik cair ini memastikan penyerapan nitrogen cepat dan efisien tanpa merusak tanah.",
    benefits: [
      "Hijau Daun Instan: Memberikan efek hijau daun yang cepat, merangsang pertumbuhan vegetatif yang subur",
      "Cepat Serap & Efisien: Nitrogen dalam bentuk organik cair lebih mudah diserap tanaman, mengurangi kehilangan nutrisi",
      "Ramah Tanah & Lingkungan: Aman bagi mikroorganisme tanah, tidak meninggalkan residu berbahaya",
    ],
    usage: {
      steps: [
        "Campurkan 5-10 ml Urea Dokter Tani per liter air",
        "Semprotkan ke seluruh bagian tanaman atau siramkan ke area perakaran",
        "Aplikasikan setiap 7-14 hari pada fase pertumbuhan vegetatif",
      ],
      image: "/Katalog Dokter Tani/urea/images/urea_03.jpg",
    },
    cta: "Berikan nutrisi nitrogen terbaik untuk tanaman Anda. Dapatkan Urea Dokter Tani Sekarang & Nikmati Daun Hijau Subur Tanpa Khawatir!",
    reviews: [
      { id: "r67", name: "Pak Sudarman", rating: 5, date: "2025-12-09", comment: "Tanaman langsung hijau segar dalam 3 hari! Dan tanah tetap gembur, tidak masam." },
      { id: "r68", name: "Mas Galih", rating: 5, date: "2025-11-26", comment: "Pengganti urea kimia yang sempurna. Ramah tanah dan hasilnya nyata." },
    ],
    relatedProductIds: ["3", "30", "22"],
    ecommerceLinks: { shopee: "#", tokopedia: "#", lazada: "#", tiktokShop: "#" },
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getRelatedProducts(product: Product): Product[] {
  return product.relatedProductIds
    .map((id) => getProductById(id))
    .filter(Boolean) as Product[];
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getAllCategories(): string[] {
  return Array.from(new Set(products.map((p) => p.category)));
}

